2018-12-09 11:08:37 DEBUG db_query [db.py-21] ()
2018-12-09 11:08:37 DEBUG _new_conn [connectionpool.py-205] Starting new HTTP connection (1): 115.28.108.130:5000
2018-12-09 11:08:37 DEBUG _make_request [connectionpool.py-393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 122
2018-12-09 11:08:37 INFO log_case_info [test_log.py-4] --------------------------------------------------
2018-12-09 11:08:37 INFO log_case_info [test_log.py-5] 执行用例: test_user_reg_normal
2018-12-09 11:08:37 INFO log_case_info [test_log.py-6] 接口地址: http://115.28.108.130:5000/api/user/reg/
2018-12-09 11:08:37 INFO log_case_info [test_log.py-7] 请求数据:  {"name": "孙悟空", "password": "123456"}
2018-12-09 11:08:37 INFO log_case_info [test_log.py-8] 期望结果: {
    "code": "100000",
    "data": {
        "name": "孙悟空",
        "password": "e10adc3949ba59abbe56e057f20f883e"
    },
    "msg": "成功"
}
2018-12-09 11:08:37 INFO log_case_info [test_log.py-9] 实际结果: {"code":"100000","data":{"name":"\u5b59\u609f\u7a7a","password":"e10adc3949ba59abbe56e057f20f883e"},"msg":"\u6210\u529f"}

2018-12-09 11:08:37 DEBUG db_query [db.py-21] ((9695, '孙悟空', 'e10adc3949ba59abbe56e057f20f883e'),)
2018-12-09 11:08:37 DEBUG db_change [db.py-30] delete from user where name = '孙悟空'
2018-12-09 11:08:37 DEBUG _new_conn [connectionpool.py-205] Starting new HTTP connection (1): 115.28.108.130:5000
2018-12-09 11:08:37 DEBUG _make_request [connectionpool.py-393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 158
2018-12-09 11:08:37 INFO log_case_info [test_log.py-4] --------------------------------------------------
2018-12-09 11:08:37 INFO log_case_info [test_log.py-5] 执行用例: test_user_reg_normal
2018-12-09 11:08:37 INFO log_case_info [test_log.py-6] 接口地址: http://115.28.108.130:5000/api/user/reg/
2018-12-09 11:08:37 INFO log_case_info [test_log.py-7] 请求数据:  {"name": "李元芳", "password": "123456"}
2018-12-09 11:08:37 INFO log_case_info [test_log.py-8] 期望结果: {
    "code": "100001",
    "data": {
        "name": "李元芳",
        "password": "e10adc3949ba59abbe56e057f20f883e"
    },
    "msg": "失败，用户已存在"
}
2018-12-09 11:08:37 INFO log_case_info [test_log.py-9] 实际结果: {"code":"100001","data":{"name":"\u674e\u5143\u82b3","password":"e10adc3949ba59abbe56e057f20f883e"},"msg":"\u5931\u8d25\uff0c\u7528\u6237\u5df2\u5b58\u5728"}

2018-12-09 12:13:14 DEBUG db_query [db.py-21] ((857, '李元芳', 'e10adc3949ba59abbe56e057f20f883e'),)
2018-12-09 12:13:14 INFO <module> [run.py-13] 测试开始==================================================
2018-12-09 12:13:14 DEBUG _new_conn [connectionpool.py-205] Starting new HTTP connection (1): 115.28.108.130:5000
2018-12-09 12:13:14 DEBUG _make_request [connectionpool.py-393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
2018-12-09 12:13:14 INFO log_case_info [test_log.py-4] --------------------------------------------------
2018-12-09 12:13:14 INFO log_case_info [test_log.py-5] 执行用例: test_user_login_normal
2018-12-09 12:13:14 INFO log_case_info [test_log.py-6] 接口地址: http://115.28.108.130:5000/api/user/login/
2018-12-09 12:13:14 INFO log_case_info [test_log.py-7] 请求数据:  {"name": "李元芳", "password": "123456"}
2018-12-09 12:13:14 INFO log_case_info [test_log.py-8] 期望结果: <h1>登录成功</h1>
2018-12-09 12:13:14 INFO log_case_info [test_log.py-9] 实际结果: <h1>登录成功</h1>
2018-12-09 12:13:14 DEBUG _new_conn [connectionpool.py-205] Starting new HTTP connection (1): 115.28.108.130:5000
2018-12-09 12:13:14 DEBUG _make_request [connectionpool.py-393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
2018-12-09 12:13:14 INFO log_case_info [test_log.py-4] --------------------------------------------------
2018-12-09 12:13:14 INFO log_case_info [test_log.py-5] 执行用例: test_user_login_password_wrong
2018-12-09 12:13:14 INFO log_case_info [test_log.py-6] 接口地址: http://115.28.108.130:5000/api/user/login/
2018-12-09 12:13:14 INFO log_case_info [test_log.py-7] 请求数据:  {"name": "张三", "password": "1234567"}
2018-12-09 12:13:14 INFO log_case_info [test_log.py-8] 期望结果: <h1>失败，用户名或密码错误</h1>
2018-12-09 12:13:14 INFO log_case_info [test_log.py-9] 实际结果: <h1>失败，用户名或密码错误</h1>
2018-12-09 12:13:14 DEBUG db_query [db.py-21] ()
2018-12-09 12:13:14 DEBUG _new_conn [connectionpool.py-205] Starting new HTTP connection (1): 115.28.108.130:5000
2018-12-09 12:13:14 DEBUG _make_request [connectionpool.py-393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 122
2018-12-09 12:13:14 INFO log_case_info [test_log.py-4] --------------------------------------------------
2018-12-09 12:13:14 INFO log_case_info [test_log.py-5] 执行用例: test_user_reg_normal
2018-12-09 12:13:14 INFO log_case_info [test_log.py-6] 接口地址: http://115.28.108.130:5000/api/user/reg/
2018-12-09 12:13:14 INFO log_case_info [test_log.py-7] 请求数据:  {"name": "孙悟空", "password": "123456"}
2018-12-09 12:13:14 INFO log_case_info [test_log.py-8] 期望结果: {
    "code": "100000",
    "data": {
        "name": "孙悟空",
        "password": "e10adc3949ba59abbe56e057f20f883e"
    },
    "msg": "成功"
}
2018-12-09 12:13:14 INFO log_case_info [test_log.py-9] 实际结果: {"code":"100000","data":{"name":"\u5b59\u609f\u7a7a","password":"e10adc3949ba59abbe56e057f20f883e"},"msg":"\u6210\u529f"}

2018-12-09 12:13:14 DEBUG db_query [db.py-21] ((9702, '孙悟空', 'e10adc3949ba59abbe56e057f20f883e'),)
2018-12-09 12:13:14 DEBUG db_change [db.py-30] delete from user where name = '孙悟空'
2018-12-09 12:13:14 DEBUG _new_conn [connectionpool.py-205] Starting new HTTP connection (1): 115.28.108.130:5000
2018-12-09 12:13:14 DEBUG _make_request [connectionpool.py-393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 158
2018-12-09 12:13:14 INFO log_case_info [test_log.py-4] --------------------------------------------------
2018-12-09 12:13:14 INFO log_case_info [test_log.py-5] 执行用例: test_user_reg_normal
2018-12-09 12:13:14 INFO log_case_info [test_log.py-6] 接口地址: http://115.28.108.130:5000/api/user/reg/
2018-12-09 12:13:14 INFO log_case_info [test_log.py-7] 请求数据:  {"name": "李元芳", "password": "123456"}
2018-12-09 12:13:14 INFO log_case_info [test_log.py-8] 期望结果: {
    "code": "100001",
    "data": {
        "name": "李元芳",
        "password": "e10adc3949ba59abbe56e057f20f883e"
    },
    "msg": "失败，用户已存在"
}
2018-12-09 12:13:14 INFO log_case_info [test_log.py-9] 实际结果: {"code":"100001","data":{"name":"\u674e\u5143\u82b3","password":"e10adc3949ba59abbe56e057f20f883e"},"msg":"\u5931\u8d25\uff0c\u7528\u6237\u5df2\u5b58\u5728"}

2018-12-09 12:26:59 DEBUG db_query [db.py-21] ((857, '李元芳', 'e10adc3949ba59abbe56e057f20f883e'),)
2018-12-09 12:26:59 INFO <module> [run.py-13] 测试开始==================================================
2018-12-09 12:26:59 DEBUG _new_conn [connectionpool.py-205] Starting new HTTP connection (1): 115.28.108.130:5000
2018-12-09 12:26:59 DEBUG _make_request [connectionpool.py-393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
2018-12-09 12:26:59 INFO log_case_info [test_log.py-4] --------------------------------------------------
2018-12-09 12:26:59 INFO log_case_info [test_log.py-5] 执行用例: test_user_login_normal
2018-12-09 12:26:59 INFO log_case_info [test_log.py-6] 接口地址: http://115.28.108.130:5000/api/user/login/
2018-12-09 12:26:59 INFO log_case_info [test_log.py-7] 请求数据:  {"name": "李元芳", "password": "123456"}
2018-12-09 12:26:59 INFO log_case_info [test_log.py-8] 期望结果: <h1>登录成功</h1>
2018-12-09 12:26:59 INFO log_case_info [test_log.py-9] 实际结果: <h1>登录成功</h1>
2018-12-09 12:26:59 DEBUG _new_conn [connectionpool.py-205] Starting new HTTP connection (1): 115.28.108.130:5000
2018-12-09 12:26:59 DEBUG _make_request [connectionpool.py-393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
2018-12-09 12:26:59 INFO log_case_info [test_log.py-4] --------------------------------------------------
2018-12-09 12:26:59 INFO log_case_info [test_log.py-5] 执行用例: test_user_login_password_wrong
2018-12-09 12:26:59 INFO log_case_info [test_log.py-6] 接口地址: http://115.28.108.130:5000/api/user/login/
2018-12-09 12:26:59 INFO log_case_info [test_log.py-7] 请求数据:  {"name": "张三", "password": "1234567"}
2018-12-09 12:26:59 INFO log_case_info [test_log.py-8] 期望结果: <h1>失败，用户名或密码错误</h1>
2018-12-09 12:26:59 INFO log_case_info [test_log.py-9] 实际结果: <h1>失败，用户名或密码错误</h1>
2018-12-09 12:26:59 DEBUG db_query [db.py-21] ()
2018-12-09 12:26:59 DEBUG _new_conn [connectionpool.py-205] Starting new HTTP connection (1): 115.28.108.130:5000
2018-12-09 12:26:59 DEBUG _make_request [connectionpool.py-393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 122
2018-12-09 12:26:59 INFO log_case_info [test_log.py-4] --------------------------------------------------
2018-12-09 12:26:59 INFO log_case_info [test_log.py-5] 执行用例: test_user_reg_normal
2018-12-09 12:26:59 INFO log_case_info [test_log.py-6] 接口地址: http://115.28.108.130:5000/api/user/reg/
2018-12-09 12:26:59 INFO log_case_info [test_log.py-7] 请求数据:  {"name": "孙悟空", "password": "123456"}
2018-12-09 12:26:59 INFO log_case_info [test_log.py-8] 期望结果: {
    "code": "100000",
    "data": {
        "name": "孙悟空",
        "password": "e10adc3949ba59abbe56e057f20f883e"
    },
    "msg": "成功"
}
2018-12-09 12:26:59 INFO log_case_info [test_log.py-9] 实际结果: {"code":"100000","data":{"name":"\u5b59\u609f\u7a7a","password":"e10adc3949ba59abbe56e057f20f883e"},"msg":"\u6210\u529f"}

2018-12-09 12:27:00 DEBUG db_query [db.py-21] ((9710, '孙悟空', 'e10adc3949ba59abbe56e057f20f883e'),)
2018-12-09 12:27:00 DEBUG db_change [db.py-30] delete from user where name = '孙悟空'
2018-12-09 12:27:00 DEBUG _new_conn [connectionpool.py-205] Starting new HTTP connection (1): 115.28.108.130:5000
2018-12-09 12:27:00 DEBUG _make_request [connectionpool.py-393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 158
2018-12-09 12:27:00 INFO log_case_info [test_log.py-4] --------------------------------------------------
2018-12-09 12:27:00 INFO log_case_info [test_log.py-5] 执行用例: test_user_reg_normal
2018-12-09 12:27:00 INFO log_case_info [test_log.py-6] 接口地址: http://115.28.108.130:5000/api/user/reg/
2018-12-09 12:27:00 INFO log_case_info [test_log.py-7] 请求数据:  {"name": "李元芳", "password": "123456"}
2018-12-09 12:27:00 INFO log_case_info [test_log.py-8] 期望结果: {
    "code": "100001",
    "data": {
        "name": "李元芳",
        "password": "e10adc3949ba59abbe56e057f20f883e"
    },
    "msg": "失败，用户已存在"
}
2018-12-09 12:27:00 INFO log_case_info [test_log.py-9] 实际结果: {"code":"100001","data":{"name":"\u674e\u5143\u82b3","password":"e10adc3949ba59abbe56e057f20f883e"},"msg":"\u5931\u8d25\uff0c\u7528\u6237\u5df2\u5b58\u5728"}

2018-12-09 12:29:44 DEBUG db_query [db.py-21] ((857, '李元芳', 'e10adc3949ba59abbe56e057f20f883e'),)
2018-12-09 12:29:44 INFO <module> [run.py-13] 测试开始==================================================
2018-12-09 12:29:44 DEBUG _new_conn [connectionpool.py-205] Starting new HTTP connection (1): 115.28.108.130:5000
2018-12-09 12:29:45 DEBUG _make_request [connectionpool.py-393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
2018-12-09 12:29:45 INFO log_case_info [test_log.py-4] --------------------------------------------------
2018-12-09 12:29:45 INFO log_case_info [test_log.py-5] 执行用例: test_user_login_normal
2018-12-09 12:29:45 INFO log_case_info [test_log.py-6] 接口地址: http://115.28.108.130:5000/api/user/login/
2018-12-09 12:29:45 INFO log_case_info [test_log.py-7] 请求数据:  {"name": "李元芳", "password": "123456"}
2018-12-09 12:29:45 INFO log_case_info [test_log.py-8] 期望结果: <h1>登录成功</h1>
2018-12-09 12:29:45 INFO log_case_info [test_log.py-9] 实际结果: <h1>登录成功</h1>
2018-12-09 12:29:45 DEBUG _new_conn [connectionpool.py-205] Starting new HTTP connection (1): 115.28.108.130:5000
2018-12-09 12:29:45 DEBUG _make_request [connectionpool.py-393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
2018-12-09 12:29:45 INFO log_case_info [test_log.py-4] --------------------------------------------------
2018-12-09 12:29:45 INFO log_case_info [test_log.py-5] 执行用例: test_user_login_password_wrong
2018-12-09 12:29:45 INFO log_case_info [test_log.py-6] 接口地址: http://115.28.108.130:5000/api/user/login/
2018-12-09 12:29:45 INFO log_case_info [test_log.py-7] 请求数据:  {"name": "张三", "password": "1234567"}
2018-12-09 12:29:45 INFO log_case_info [test_log.py-8] 期望结果: <h1>失败，用户名或密码错误</h1>
2018-12-09 12:29:45 INFO log_case_info [test_log.py-9] 实际结果: <h1>失败，用户名或密码错误</h1>
2018-12-09 12:29:45 DEBUG db_query [db.py-21] ()
2018-12-09 12:29:45 DEBUG _new_conn [connectionpool.py-205] Starting new HTTP connection (1): 115.28.108.130:5000
2018-12-09 12:29:45 DEBUG _make_request [connectionpool.py-393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 122
2018-12-09 12:29:45 INFO log_case_info [test_log.py-4] --------------------------------------------------
2018-12-09 12:29:45 INFO log_case_info [test_log.py-5] 执行用例: test_user_reg_normal
2018-12-09 12:29:45 INFO log_case_info [test_log.py-6] 接口地址: http://115.28.108.130:5000/api/user/reg/
2018-12-09 12:29:45 INFO log_case_info [test_log.py-7] 请求数据:  {"name": "孙悟空", "password": "123456"}
2018-12-09 12:29:45 INFO log_case_info [test_log.py-8] 期望结果: {
    "code": "100000",
    "data": {
        "name": "孙悟空",
        "password": "e10adc3949ba59abbe56e057f20f883e"
    },
    "msg": "成功"
}
2018-12-09 12:29:45 INFO log_case_info [test_log.py-9] 实际结果: {"code":"100000","data":{"name":"\u5b59\u609f\u7a7a","password":"e10adc3949ba59abbe56e057f20f883e"},"msg":"\u6210\u529f"}

2018-12-09 12:29:45 DEBUG db_query [db.py-21] ((9714, '孙悟空', 'e10adc3949ba59abbe56e057f20f883e'),)
2018-12-09 12:29:45 DEBUG db_change [db.py-30] delete from user where name = '孙悟空'
2018-12-09 12:29:45 DEBUG _new_conn [connectionpool.py-205] Starting new HTTP connection (1): 115.28.108.130:5000
2018-12-09 12:29:45 DEBUG _make_request [connectionpool.py-393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 158
2018-12-09 12:29:45 INFO log_case_info [test_log.py-4] --------------------------------------------------
2018-12-09 12:29:45 INFO log_case_info [test_log.py-5] 执行用例: test_user_reg_normal
2018-12-09 12:29:45 INFO log_case_info [test_log.py-6] 接口地址: http://115.28.108.130:5000/api/user/reg/
2018-12-09 12:29:45 INFO log_case_info [test_log.py-7] 请求数据:  {"name": "李元芳", "password": "123456"}
2018-12-09 12:29:45 INFO log_case_info [test_log.py-8] 期望结果: {
    "code": "100001",
    "data": {
        "name": "李元芳",
        "password": "e10adc3949ba59abbe56e057f20f883e"
    },
    "msg": "失败，用户已存在"
}
2018-12-09 12:29:45 INFO log_case_info [test_log.py-9] 实际结果: {"code":"100001","data":{"name":"\u674e\u5143\u82b3","password":"e10adc3949ba59abbe56e057f20f883e"},"msg":"\u5931\u8d25\uff0c\u7528\u6237\u5df2\u5b58\u5728"}

2018-12-09 12:29:45 INFO <module> [run.py-19] 发送邮件成功
2018-12-09 12:29:45 INFO <module> [run.py-20] 测试结束==================================================
